---
title: "Conclusion"
---

**What we find:**


This project set out to construct a predictive model of chocolate rating, given certain chocolate ingredients. 

In this study, three main machine learning algorithms were used, including linear regression, Random Forest model and K-nearest Neighbors model. To approach better performance, cross validation and Ridge penalization was conducted to improve the modeling. The RMSE was computed and compared to search for the best algorithm. As the top performer, the Random Forest model in this project minimized the RMSE to **0.4331**. 


In this project, cocoa percentage was found to have most significant predictive power for chocolate rating. Certain ingredients, including vanilla, lecithin and sugar, also affect its flavor test. 

According to the chocolate manufacture, the cocoa content is a representative of the formulation of chocolate, which characterizes the overall tasting experience of the chocolate. The addition of vanilla gives a floral, buttery aroma and added sugar offers a sweet, balance with the bitterness of cocoa content. The lecithin is an emulsifier added to improve the viscosity (“flowability”) of the chocolate when it is melted. The ingredients and characteristics discussed above can be used to predict the flavor rating of the chocolate based on the model.

**Futher Improvement**

Further investigation could be testing predictive model on larger dataset, including chocolate-flavor food product. More analysis on the relationship between chocolate bean, manufacturer and rating can be develop to establish a greater degree of accuracy in prediction.
